Draft: Fix wrong nodejs detection
redhat-developer/alizer pull request #156
Opened 2023-03-25 00:20 UTC by thepetk

## What does this PR do?

It adds a list of `configuration_files` inside the `languages-customization.yaml` file:

```yaml
Python:
  configuration_files:
    - "manage.py"
    - "app.py"
    - "config.py"
    - "__init__.py"
  component: true
  ```
This allows the `component_recognizer` to be able to recognize `Python` components, from their `configuration_files`, in given projects.

It also creates the `FlaskDetector` which allows the `PythonEnricher` to recognize `flask` as framework of a `python` project.

## Which issue(s) this PR fixes:

https://github.com/redhat-developer/alizer/issues/147

2023-03-30 20:10 UTC, mike-hoang commented on go/pkg/apis/enricher/framework/python/django_detector.go
> +	projectToml := utils.GetFile(files, "project.toml")
should this be `pyproject.toml` instead?

2023-03-31 08:35 UTC, kadel requested changes

2023-03-31 08:54 UTC, thepetk commented
@kadel / @mike-hoang I've updated the `pyproject` filename according to [PEP 621](https://peps.python.org/pep-0621/)

2023-03-31 12:35 UTC, kadel commented
Component detections seem to work ok.

<details>
 <summary>testing output</summary>

```
go run alizer.go devfile ~/DEMO/vote/pipelines-vote-ui/
[
	{
		"Name": "python",
		"Language": "Python",
		"ProjectType": "Python",
		"Tags": [
			"Python",
			"Pip",
			"Flask"
		]
	}
]

go run alizer.go component ~/DEMO/vote/pipelines-vote-ui/
[
	{
		"Name": "pipelines-vote-ui",
		"Path": "/Users/tkral/DEMO/vote/pipelines-vote-ui/",
		"Languages": [
			{
				"Name": "Python",
				"Aliases": [
					"python3",
					"rusthon"
				],
				"Weight": 100,
				"Frameworks": [
					"Flask"
				],
				"Tools": [],
				"CanBeComponent": true
			}
		],
		"Ports": [
			8080
		]
	}
]
```
</details>

But language `recognizer.Analyze` detection still marks this repo as JavaScript.

I guess this goes back to the issue that this function uses only the number of files grouped by extension as a metric.

This PR fixes the most pressing issue (component detection), but the original issues should be kept open until the language detection is more robust. 










<details>
 <summary>testing output</summary>

```
go run alizer.go analyze ~/DEMO/vote/pipelines-vote-ui/
[
	{
		"Name": "JavaScript",
		"Aliases": [
			"js",
			"node",
			"nodejs",
			"TypeScript"
		],
		"Weight": 66.66,
		"Frameworks": [],
		"Tools": [],
		"CanBeComponent": true
	},
	{
		"Name": "Python",
		"Aliases": [
			"python3",
			"rusthon"
		],
		"Weight": 33.33,
		"Frameworks": [
			"Flask"
		],
		"Tools": [],
		"CanBeComponent": true
	}
]
```


</details>

2023-03-31 12:36 UTC, kadel approved these changes

2023-03-31 13:51 UTC, thepetk commented
Sure @kadel , I'll follow up on the issue to clarify this.

2023-03-31 13:51 UTC, mike-hoang approved these changes

2023-03-31 14:00 UTC, merged