Add basic cli
redhat-developer/alizer pull request #9
Opened 2021-02-12 16:55 UTC by lstocchi

it resolves #2

2021-02-12 17:46 UTC, jeffmaury requested changes
Also I tried to run the native binary:

./cli-0.1.0-SNAPSHOT-runner .
java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:167)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:113)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:921)
	at org.apache.commons.io.IOUtils.toString(IOUtils.java:2681)
	at org.apache.commons.io.IOUtils.toString(IOUtils.java:2661)
	at com.redhat.devtools.recognizer.api.LanguageFileHandler.initLanguages(LanguageFileHandler.java:46)
	at com.redhat.devtools.recognizer.api.LanguageFileHandler.<init>(LanguageFileHandler.java:34)
	at com.redhat.devtools.recognizer.api.LanguageFileHandler.get(LanguageFileHandler.java:39)
	at com.redhat.devtools.recognizer.api.LanguageRecognizerImpl.analyze(LanguageRecognizerImpl.java:38)
	at com.redhat.devtools.recognizer.cli.AlizerCli.run(AlizerCli.java:32)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at io.quarkus.picocli.runtime.PicocliRunner$EventExecutionStrategy.execute(PicocliRunner.java:26)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at io.quarkus.picocli.runtime.PicocliRunner.run(PicocliRunner.java:39)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:119)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:30)

2021-02-12 17:46 UTC, jeffmaury commented on cli/pom.xml
> +    <compiler-plugin.version>3.8.1</compiler-plugin.version>
Not sure the non quarkus properties are required as they are probably herited from jboss-parent, to be checked

2021-02-12 17:46 UTC, jeffmaury commented on cli/pom.xml
> +          <version>0.1.0-SNAPSHOT</version>
Use ${project.version}

2021-02-12 17:46 UTC, jeffmaury commented on cli/src/main/java/com/redhat/devtools/recognizer/cli/AlizerCli.java
> +                                    (!lang.getFrameworks().isEmpty() ? lang.getFrameworks().get(0) : ""),
Better display all framework with String.join

2021-02-12 17:46 UTC, jeffmaury commented on cli/src/main/java/com/redhat/devtools/recognizer/cli/AlizerCli.java
> +                                    (!lang.getTools().isEmpty() ? lang.getTools().get(0) : ""),
Idem

2021-02-15 16:50 UTC, jeffmaury requested changes
Tested it but native mode is working in a degraded mode. If you go to cli/target and run cli-0.1.0-SNAPSHOT-runner then you will get Java 100%. If you run java -jar cli-0.1.0-SNAPSHOT-runner.jar you will get Java Quarkus Maven 100%

See https://quarkus.io/guides/all-config#quarkus-core_quarkus.native.auto-service-loader-registration

2021-02-15 17:02 UTC, lstocchi commented
> Tested it but native mode is working in a degraded mode. If you go to cli/target and run cli-0.1.0-SNAPSHOT-runner then you will get Java 100%. If you run java -jar cli-0.1.0-SNAPSHOT-runner.jar you will get Java Quarkus Maven 100%
> 
> See https://quarkus.io/guides/all-config#quarkus-core_quarkus.native.auto-service-loader-registration

I did the tests before to push and i was convinced it was working fine lol ... better to stop for today :laughing: BTW with that property works fine, thanks!!

2021-03-01 16:15 UTC, jeffmaury approved these changes
LGTM

2021-03-01 19:02 UTC, merged